config/routes.rb
KhandipIn::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  resources :users
  resources :sessions
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  include BCrypt

  EMAIL_REGEX = /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  MAX_COLUMN_LENGTH = 255
  attr_accessor :password, :password_confirmation

  
  validates :password, presence: true, if: :password_required?
  validates :password, length: { minimum: 6, maximum: 20 }, allow_blank: true

  validates :email,
            format: { with: EMAIL_REGEX }
  validates :email, presence: true
  validates :email,
            uniqueness: { case_sensitive: false},
            allow_blank: true
  validates :email, length: { maximum: MAX_COLUMN_LENGTH }

  validates :password, confirmation: true, if: :password_required?
  validates :password_confirmation, presence: true, if: :password_required?

  before_save :encrypt_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def password_required?
    !persisted? || !password.nil?
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	end

	def create
	  user = User.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to root_url, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth</title>
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="user_nav" class='nav'>
  <%= render '/shared/header' %>

  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

<%= render '/shared/footer' %>

</body>
</html>

app/views/shared/_footer.html.erb
<div id="footer" class="content pure-u-1">
<div class="pure-g-r">
<div class="pure-u-1-5">
<h3>Company</h3>
<ul>
<li><a href="/privacy_policy">Privacy Policy</a></li>
</ul>
</div>
<!--2nd col -->
<div class="pure-u-1-5">
<h3>Products</h3>
<ul>
<li><a href="/tos">Terms of Service</a></li>
</ul>
</div>
<!--3rd col -->
<div class="pure-u-1-5">
<h3>Policy</h3>
<ul>
<li><a href="#">Lorel ipsum</a></li>
</ul>
</div>
<!--4th col -->
<div class="pure-u-1-5">
<h3>Social</h3>
<ul>
<li><a href="#"><img src="images/gplus.png"></a></li>
</ul>
</div>
</div>
</div>

app/views/shared/_header.html.erb
<div id="top-menu" class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
  <a href="" class="pure-menu-heading">KhandipIn</a>
  <ul>
    <li class="pure-menu-selected"><a href="home.html">Home</a></li>
    <li><a href="">Pricing</a></li>
    <li><a href="">Contact</a></li>
  </ul>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user, html:  {class: 'pure-form'} do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="pure-button pure-button-primary"><%= f.submit %></p>
<% end %>